#
# THIS IS DEVELOPMENT COMPOSE FILE
#

#docker-compose -f docker-compose.yml up -d
version: '3.7'

services:
  library:
    build: .
    container_name: library
    working_dir: /var/www/php
    volumes:
      - $PWD:/var/www/php
    ports:
      - 9035:9035
    command: php -S 0.0.0.0:9035
    # -t /var/www/php #tail -f /dev/null
    #php -S localhost:port -t your_folder/
    networks:
      - database_mysql

networks:
  database_mysql:
    external: true