#docker-compose up -d
version: '3.7'

services:
  library:
    image: php:8.0-apache
    container_name: library
    working_dir: /var/www/php
    volumes:
      - $PWD:/var/www/php
    ports:
      - 9035:9035
    command: sh -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && php -S 0.0.0.0:9035"
    #php -S localhost:port -t your_folder/
    networks:
      - database_mysql

networks:
  database_mysql:
    external: true